trigger:
  - none

stages:
  - stage: build
    displayName: Build Stage
    jobs:
    - job: MavenPackageTestAndPublishArtifacts
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          pmdRunAnalysis: true

        # - task: copyFile@2
        #   displayName: Copy jar file to artifact repository
        #   inputs:
        #     sourceFolder: $(System.DefaultWorkingDirectory)
        #     contents: '**/*.jar'
        #     targetFolder: $(build.artifactstagingdirectory)

      - task: PublishPipelineArtifact@1
        displayName: 'Publish build to artifact'
        inputs:
          targetPath: 'target/azure-functions/javafunctions/*.?(war|jar)'
          #targetPath: 'target'
          artifactName: drop
          artifactType: pipeline

